### ISSUE TITLE
Molecule now requires plugins to perform schema validation (was: Error with molecule 4.0.2)

### ISSUE THREAD

**Issue by asg1612** [meffie/molecule-proxmox#3]
I'm testing molecule-proxmox, with the molecule version 4.
I created de role:

`molecule init role --driver-name proxmox asg1612.proxmox`

I try to run a test, and I get the error:

> 
> CRITICAL Failed to validate /home/informatica/Desarrollo/ansible-roles/proxmox/proxmox/molecule/default/molecule.yml
> 
> ["'proxmox' is not one of ['azure', 'ec2', 'delegated', 'docker', 'containers', 'openstack', 'podman', 'vagrant', 'digitalocean', 'gce', 'libvirt', 'lxd']"]

My molecule.yml is the original from molecule init role command.

```
---
dependency:
  name: galaxy
driver:
  name: proxmox
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
```
